version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-container
    environment:
      - PORT=${PORT}
    ports:
      - '8081:8082'
    volumes:
      - ./:/app/src